### ISSUE TITLE
fans run after wake-up from suspend

### ISSUE THREAD

**Issue by martrs** [linux-on-mac/mbpfan#148]
I noticed that every time iMac wakes up from suspend mode, the fan starts running. I use Fedora 27 with systemd running the mbpfan daemon on a  2012 iMac.

The fan was quiet before suspend, so I don't think any processing changed since then.
I waited for several polling intervals (like a minute) but no change in fan speed.

The only time the fan becomes quiet again is if I restart the daemon using systemctl restart mbpfan.service.

Does the daemon detect wakeup from suspend properly?

**Comment by dgraziotin** [comment]
Hello, mbpfan is not supposed to be bothered by suspend/wakeup, but it is worth investigating. 
Are you using Fedora's default kernel, which I think is 4.13.x? 
I have a 2016 iMac at work, will also check again what happens when suspending.

**Comment by martrs** [comment]
I've been using Fedora 27 kernel since 4.11, now running 4.13.11. Same issue throughout.

I should also mention that I've replaced CDROM with 2nd HDD, and I used to use Mac Fan Control in OSX to pair the CDROM fan to HDD temp sensor rather than to CDROM temp sensor which was removed with the CDROM. I wonder if this has anything to do with it.

It seems like mbpfan has no control over this mechanism when resume occurs (I'm guessing the fan is started by the system after resume, not by mbpfan). It looks like restarting mbpfan indirectly triggers this mechanism to properly reset.

If that's the case, any way for mbpfan to control this mechanism, whatever that is? Or can we have mbpfan just restart itself after suspend?

**Comment by gaul** [comment]
Can `mbpfan` reliably detect or infer a suspend event?  Perhaps it could store the last poll time and if it detects a large jump it re-runs the "Sleeping for 2 seconds to get first temp delta" logic?

@martrs Could you test this and report back?

**Comment by Dmole** [comment]
https://wiki.archlinux.org/index.php/Power_management#Suspend/resume_service_files

**Comment by gaul** [comment]
@Dmole Could you share logs using `mbpfan -f -v` when you observe the unexpected fan spin-up before and after suspending?

**Comment by Dmole** [comment]
@gaul is there a command that outputs the value of all sensors and fans not just one of each?
Interestingly the fan noise seems to oscillate every 7 seconds just as the reading is taken.


```
Found 5 sensors
Found 3 fans
Sleeping for 2 seconds to get first temp delta
Old Temp 36: New Temp: 36, Fan Speed: 2000
Sleeping for 7 seconds
```

**Comment by gaul** [comment]
What kind of machine do you run?  mbpfan support for desktops is new and might need some tuning.  Also I wonder if you change the sleep time to 1 second (the new default) if the symptoms disappear?  At least on my MacBook, the BIOS/EFI controls the fan until mbpfan overrides it.

**Comment by Dmole** [comment]
> What kind of machine do you run? 

old iMac A1312

> if you change the sleep time to 1 second (the new default) if the symptoms disappear?

As mentioned on the PR they change but don't disappear.

> the BIOS/EFI controls the fan until mbpfan overrides it

The issue sounds like mbpfan partly loses control of 1 (of 3) fan to EFI after suspend because the sound is nowhere near as loud as during boot.

**Comment by gaul** [comment]
`mbpfan` has some outdated assumptions about a single fan with a single process package, e.g., MacBooks.  @atisharma did some work in #165 to fix this but agree that we should output all the temperatures and fan speeds in verbose mode.  This is straightforward to do, can either of you do this since I lack this hardware?

**Comment by Dmole** [comment]
What my system looks like;

```
cat /sys/devices/platform/coretemp.*/hwmon/hwmon0/temp*_input
47000
47000
47000
47000
47000

cd /sys/devices/platform/applesmc.768/ && grep . temp*
temp10_input:45000
temp10_label:TC2c
temp11_input:45000
temp11_label:TC3c
temp12_input:44000
temp12_label:TCGc
temp13_input:45000
temp13_label:TCSc
temp14_input:46500
temp14_label:TCXc
temp15_input:56000
temp15_label:TG0D
temp16_input:53250
temp16_label:TG0H
temp17_input:56000
temp17_label:TG0d
temp18_input:53250
temp18_label:TG0h
temp19_input:53000
temp19_label:TG0p
temp1_input:20250
temp1_label:TA0P
temp20_input:9000
temp20_label:TH0O
temp21_input:9000
temp21_label:TH1O
temp22_input:22500
temp22_label:TL0P
temp23_input:38500
temp23_label:TL0V
temp24_input:36250
temp24_label:TL0p
temp25_input:39500
temp25_label:TL1P
temp26_input:31500
temp26_label:TL1V
temp27_input:39500
temp27_label:TL1p
temp28_input:31500
temp28_label:TL1v
temp29_input:38750
temp29_label:TL2V
temp2_input:21000
temp2_label:TA0V
temp30_input:38750
temp30_label:TLAV
temp31_input:31500
temp31_label:TLBV
temp32_input:38500
temp32_label:TLCV
temp33_input:35750
temp33_label:TO0P
temp34_input:36750
temp34_label:TO0p
temp35_input:61000
temp35_label:TPCD
temp36_input:35250
temp36_label:TS0P
temp37_input:30250
temp37_label:TS0V
temp38_input:35250
temp38_label:TS0p
temp39_input:34500
temp39_label:TS2P
temp3_input:26000
temp3_label:TA0p
temp40_input:32500
temp40_label:TS2V
temp41_input:34500
temp41_label:TS2p
temp42_input:44500
temp42_label:Tm0P
temp43_input:44500
temp43_label:Tm0p
temp44_input:51500
temp44_label:Tp1P
temp45_input:51500
temp45_label:Tp1p
temp46_input:52750
temp46_label:Tp2H
temp47_input:52750
temp47_label:Tp2h
temp48_input:55500
temp48_label:Tp3H
temp49_input:55500
temp49_label:Tp3h
temp4_input:45250
temp4_label:TC0H
temp5_input:45000
temp5_label:TC0P
temp6_input:45000
temp6_label:TC0c
temp7_input:45250
temp7_label:TC0h
temp8_input:45000
temp8_label:TC0p
temp9_input:45000
temp9_label:TC1c


cd /sys/devices/platform/applesmc.768/ && grep . fan*_{label,input,min,max,output,manual}
fan1_label:ODD 
fan2_label:HDD 
fan3_label:CPU 
fan1_input:1149
fan2_input:1268
fan3_input:939
fan1_min:1150
fan2_min:1100
fan3_min:940
fan1_max:2500
fan2_max:5500
fan3_max:2100
fan1_output:1150
fan2_output:1100
fan3_output:940
fan1_manual:1
fan2_manual:1
fan3_manual:1
```
I'm tempted to replace the 4000 lines of c with 40 lines of bash but I should sleep instead.

**Comment by gaul** [comment]
Could you try testing again with https://github.com/gaul/mbpfan/tree/no-caching?

**Comment by Dmole** [comment]
> Could you try testing again with https://github.com/gaul/mbpfan/tree/no-caching?

Did not help; one of the fans oscillates to an ever increasing speed after suspend, and mbpfan reports speed as unchanging, while the kernel/bash reports different numbers

```
...
Fan: ODD Old Temp 54: New Temp: 54 Speed: 1150
Fan: HDD Old Temp 54: New Temp: 54 Speed: 1100
Fan: CPU Old Temp 54: New Temp: 54 Speed: 940
...
```

```
cd /sys/devices/platform/applesmc.768/ && grep . fan*_{label,input,output}
fan1_label:ODD 
fan2_label:HDD 
fan3_label:CPU 

fan1_input:1147
fan2_input:1760
fan3_input:939

fan1_output:1150
fan2_output:2684
fan3_output:940

grep . fan*_{input,output}
fan1_input:1151
fan2_input:2742
fan3_input:938

fan1_output:1150
fan2_output:2699
fan3_output:940

```

**Comment by gaul** [comment]
Sorry this continues to cause issues -- it is hard to debug without having the hardware.  The `fan1_manual:0` sounds suggestive.  Could you try the updated https://github.com/gaul/mbpfan/tree/recalibrate branch?

**Comment by Dmole** [comment]
Thanks that fixed the issue, please get it merged into master.

**Comment by benji88i** [comment]
> Sorry this continues to cause issues -- it is hard to debug without having the hardware. The `fan1_manual:0` sounds suggestive. Could you try the updated https://github.com/gaul/mbpfan/tree/recalibrate branch?

Hi There,

I was wondering how to fix this issue on my system too. I am running Fedora although with the exact same issue. After wake my fan goes into a very high speed, and does not turn down. 

I clicked the link but its broken
