### ISSUE TITLE
Better Code Hub configuration

### ISSUE THREAD

**Issue by gaul** [linux-on-mac/mbpfan#166]
Presently Better Code Hub reports:

> Only the repository's owners and organization members (if the repository is an organization repository) can view its Better Code Hub results.

We should configure this for all viewers or disable it.

**Comment by dgraziotin** [comment]
I investigated this. It seems that either I am the only one able to view the BCH report or I shut it down for the project.

**Comment by gaul** [comment]
Could we disable this?  These failures just confuse contributors.

**Comment by gaul** [comment]
It appears that this is now disabled.

**Comment by gaul** [comment]
This somehow re-enabled and failed in #196.

**Comment by gaul** [comment]
Appears to be fixed/disabled.
