### ISSUE TITLE
Fedora package

### ISSUE THREAD

**Issue by gaul** [linux-on-mac/mbpfan#181]
It would be great if a volunteer can create a mbpfan package for Fedora.

**Comment by LyesSaadi** [comment]
[:3](https://gitlab.com/LyesSaadi/spec/blob/master/mbpfan/mbpfan.spec) !

I'm creating a copr repo :)! I'll post the link here as soon as it's ready!

**Comment by gaul** [comment]
This is great!  Please update the README with instructions when the package is accepted.

**Comment by LyesSaadi** [comment]
[It is :)!](https://copr.fedorainfracloud.org/coprs/lyessaadi/mbpfan/)

Copr is the equivalent of AUR.

## Fedora Workstation:

```
sudo dnf copr enable lyessaadi/mbpfan
sudo dnf install mbpfan
```

## Fedora Silverblue:

```
sudo wget https://copr.fedorainfracloud.org/coprs/lyessaadi/mbpfan/repo/fedora-rawhide/lyessaadi-mbpfan-fedora-rawhide.repo -O /etc/yum.repos.d/lyessaadi-mbpfan.repo
rpm-ostree install mbpfan
```

**Comment by LyesSaadi** [comment]
Do you want me to try to submit it to the official repo ?
I've never done it, but I could try to.
Also, I don't think that I would be able to do so as Fedora refuses new packages, as soon as the Beta (or final) release is reached, which already is the case (or nearly) for Fedora 31. That would mean a package would only by ready for Fedora 32.

**Comment by gaul** [comment]
It takes some effort but submitting upstream definitely gives users more trust than copr.  Don't worry about Fedora 31 or 32, I believe they will take the package immediately for the latter and will include in the former after the freeze.  But please submit a pull request with the copr instructions to the README since this is more friendly than compiling for non-developers.

**Comment by gaul** [comment]
@LyesSaadi, did you submit the package to Fedora proper?  If so could you share the Bugzilla issue?

**Comment by LyesSaadi** [comment]
Sorry, I'm overwhelmed by work recently. I can't do it and won't be able to do it, at least until mid December.

**Comment by LyesSaadi** [comment]
Hi, while reading the package guidelines, I have asked myself this question : Should this program be packaged for 32-bit arch ?

**Comment by gaul** [comment]
I believe that Fedora 31 ended support for 32-bit x86:

https://fedoraproject.org/wiki/Changes/Noi686Repositories

**Comment by LyesSaadi** [comment]
Yep, but not for Fedora 30 and 29 who are still supported. Nevertheless, I think I'll just make 64-bit packages. Those who wants to use 32-bit packages will be able to take the spec file and build it for themselves (it's pretty simple to do !).

**Comment by gaul** [comment]
Personally I would only support x86-64.  The intersection between MacBook Linux users and 32-bit distros seems quite small to me!

**Comment by LyesSaadi** [comment]
Here is the Bugzilla link tracking the progress : https://bugzilla.redhat.com/show_bug.cgi?id=1767998

**Comment by LyesSaadi** [comment]
The package was approved, I was sponsored and updates have been pushed to bodhi for testing. So, if everything goes well, it will land on stable repos in 7 days :) (Except for rawhide, where it is already in stable)!

**Comment by LyesSaadi** [comment]
> So, if everything goes well, it will land on stable repos in 7 days :)

So... Weird things are happening right now with Fedora Infrastructure??? Nothing is being pushed to testing and stable and it's Christmas so it might take longer until the issue is resolved...

If you look to [bodhi (Fedora Update Mechanism)](https://bodhi.fedoraproject.org/updates/), everything is in "pending" state...

**Comment by gaul** [comment]
Any chance that we could move this into the main Fedora repository?

**Comment by LyesSaadi** [comment]
It is already for a while now ! This issue can be safely closed :wink: !

**Comment by gaul** [comment]
Sorry I was confused!  I actually have it installed on my laptop but use master for personal use.  Verified here:

https://dl.fedoraproject.org/pub/fedora/linux/releases/33/Everything/x86_64/os/Packages/m/

Thanks again @LyesSaadi for seeing this through!
