### ISSUE TITLE
Transfer mbpfan project to gaul

### ISSUE THREAD

**Issue by dgraziotin** [linux-on-mac/mbpfan#194]
I started this project [back in 2012](https://github.com/dgraziotin/mbpfan/commit/8d89d05cf2460fad11b8e16dc4cdb503d80548b6) as a way to fix some annoyances I was having with GNU/Linux on a MacBook Pro and as a way to refresh my knowledge of C. It turned out I was not the only one annoyed with the situation. 

Since then the project has grown so much in popularity (more than 4000 unique Google entries), it has benefited from contributors at all levels (87 forks right now), and it is part of most major GNU/Linux distributions and it is loved by its users. I am proud of mbpfan and of what it has achieved.

My role in the project has diminished in the last years as I moved to other commitments in my life. First as benevolent dictator, then as an interested person. I have to thank @gaul for the strong interest shown in the project, the constant participation, and the deep knowledge of the C language, syscalls, and the Linux kernel interfaces that have made mbpfan what it is today. While I was not actively contributing anymore, I was always keeping an eye on my little project. Which is definitely in good hands right now. @gaul is also not alone. There is constant activity by a pretty cool community that I would have never imagine to see for this project six years ago.

I propose to transfer this project to @gaul. GitHub should handle all redirects so that distros and automated building systems will keep working. I hope you will accept, Andrew, and thank you so much for everything!

**Comment by gaul** [comment]
Thanks @dgraziotin!  We can transfer the project to me which is probably the least effort.  Alternatively we could create a GitHub organization which would emphasize the community effort.  I don't think this has a practical impact on the project maintenance but has different optics.

**Comment by dgraziotin** [comment]
I need you to delete your fork of mbpfan before I can transfer it to you. Otherwise GitHub tells me you already have a project with the same name.

**Comment by gaul** [comment]
Let's use the linux-on-mac organization instead of my personal account.

**Comment by dgraziotin** [comment]
Done!
