### ISSUE TITLE
Macbook with Ubuntu suspending after short time

### ISSUE THREAD

**Issue by irishane** [linux-on-mac/mbpfan#197]
Hi,

I added mbpfan using the beginners tutorial and the fans are working much quieter but now the system will suddenly suspend after watching video for 1-2 mins. I thought this could be fixed by turning off screensaver/suspend but it doesn't help, plus the intervals for it shutting down vary from ca. 1 minute up to 3 minutes or so. I think maybe the laptops suspending to avoid overheating and I've messed with the settings in mbpfan but with no joy. Any ideas here?

**Comment by gaul** [comment]
Try looking at `dmesg` output running mbpfan with the `-f -v` flags.

**Comment by gaul** [comment]
@irishane Please reopen if you have further debugging information.
