### ISSUE TITLE
sudo make tests failed

### ISSUE THREAD

**Issue by jaxsonde-ville** [linux-on-mac/mbpfan#198]
make[1]: Leaving directory '/home/cosmo/Downloads/mbpfan-master'
/usr/sbin/mbpfan -f -v -t
Starting the tests..
It is normal for them to take a bit to finish.
Using new sensor path for kernel >= 3.15.0 or some CentOS versions with kernel 3.10.0
Found hwmon path at /sys/devices/platform/coretemp.0/hwmon/hwmon2/temp
Found 5 sensors
Found 2 fans
Using new sensor path for kernel >= 3.15.0 or some CentOS versions with kernel 3.10.0
Found hwmon path at /sys/devices/platform/coretemp.0/hwmon/hwmon2/temp
Found 5 sensors
Error: Invalid Higher temp test (if fan was already spinning high, this is not worrying) 
Tests run: 3
Makefile:39: recipe for target 'tests' failed
make: *** [tests] Error 1

**Comment by jaxsonde-ville** [comment]
System:    Host: the Kernel: 4.15.0-65-generic x86_64 bits: 64 compiler: gcc v: 7.4.0 
           Desktop: Cinnamon 4.2.4 wm: muffin dm: LightDM Distro: Linux Mint 19.2 Tina 
           base: Ubuntu 18.04 bionic 
Machine:   Type: Laptop System: Apple product: MacBookPro10,1 v: 1.0 serial: <filter> Chassis: 
           type: 10 v: Mac-C3EC7CD22292981F serial: <filter> 
           Mobo: Apple model: Mac-C3EC7CD22292981F v: MacBookPro10,1 serial: <filter> UEFI: Apple 
           v: 251.0.0.0.0 date: 09/21/2018 
Battery:   ID-1: BAT0 charge: 42.1 Wh condition: 64.1/92.2 Wh (70%) volts: 12.2/10.9 
           model: SMP bq20z451 serial: N/A status: Charging 
CPU:       Topology: Quad Core model: Intel Core i7-3740QM bits: 64 type: MT MCP arch: Ivy Bridge 
           rev: 9 L2 cache: 6144 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 43100 
           Speed: 1390 MHz min/max: 1200/3700 MHz Core speeds (MHz): 1: 2116 2: 1782 3: 2108 
           4: 1553 5: 2675 6: 2584 7: 1403 8: 1298 
Graphics:  Device-1: Intel 3rd Gen Core processor Graphics vendor: Apple driver: N/A 
           bus ID: 00:02.0 chip ID: 8086:0166 
           Device-2: NVIDIA GK107M [GeForce GT 650M Mac Edition] vendor: Apple driver: N/A 
           bus ID: 01:00.0 chip ID: 10de:0fd5 
           Display: x11 server: X.Org 1.19.6 driver: fbdev unloaded: modesetting,nouveau,vesa 
           resolution: 2880x1800~91Hz 
           OpenGL: renderer: llvmpipe (LLVM 8.0 256 bits) v: 3.3 Mesa 19.0.8 compat-v: 3.1 
           direct render: Yes 
Audio:     Device-1: Intel 7 Series/C216 Family High Definition Audio driver: snd_hda_intel 
           v: kernel bus ID: 00:1b.0 chip ID: 8086:1e20 
           Device-2: NVIDIA GK107 HDMI Audio vendor: Apple driver: snd_hda_intel v: kernel 
           bus ID: 01:00.1 chip ID: 10de:0e1b 
           Sound Server: ALSA v: k4.15.0-65-generic 
Network:   Device-1: Broadcom and subsidiaries NetXtreme BCM57786 Gigabit Ethernet PCIe 
           driver: N/A port: 2000 bus ID: 03:00.0 chip ID: 14e4:16a3 
           Device-2: Broadcom and subsidiaries BCM4331 802.11a/b/g/n vendor: Apple AirPort Extreme 
           driver: wl v: kernel port: 2000 bus ID: 04:00.0 chip ID: 14e4:4331 
           IF: wlp4s0 state: up mac: <filter> 
Drives:    Local Storage: total: 495.80 GiB used: 39.98 GiB (8.1%) 
           ID-1: /dev/sda vendor: Apple model: SSD SD512E size: 465.92 GiB speed: 6.0 Gb/s 
           serial: <filter> 
           ID-2: /dev/sdb type: USB vendor: Samsung model: Flash Drive FIT size: 29.88 GiB 
           serial: <filter> 
Partition: ID-1: / size: 456.14 GiB used: 39.98 GiB (8.8%) fs: ext4 dev: /dev/dm-0 
           ID-2: swap-1 size: 976.0 MiB used: 0 KiB (0.0%) fs: swap dev: /dev/dm-1 
Sensors:   System Temperatures: cpu: 76.0 C mobo: N/A 
           Fan Speeds (RPM): N/A 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/graphics-drivers-ppa-bionic.list 
           1: deb http: //ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic main
           Active apt repos in: /etc/apt/sources.list.d/kdenlive-kdenlive-stable-bionic.list 
           1: deb http: //ppa.launchpad.net/kdenlive/kdenlive-stable/ubuntu bionic main
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //packages.linuxmint.com tina main upstream import backport
           2: deb http: //la-mirrors.evowise.com/ubuntu bionic main restricted universe multiverse
           3: deb http: //la-mirrors.evowise.com/ubuntu bionic-updates main restricted universe multiverse
           4: deb http: //la-mirrors.evowise.com/ubuntu bionic-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ bionic partner
Info:      Processes: 266 Uptime: 30m Memory: 15.57 GiB used: 2.36 GiB (15.2%) Init: systemd 
           v: 237 runlevel: 5 Compilers: gcc: 7.4.0 alt: 7 Client: Unknown python3.6 client 
           inxi: 3.0.32

**Comment by gaul** [comment]
>  Error: Invalid Higher temp test (if fan was already spinning high, this is not worrying)

Could you add some print statements to inspect the values of `temp_1` and `temp_2`?  I suspect that the fans were already spinning as the log message suggests.

**Comment by gaul** [comment]
I'm closing this since I don't have anything to act on here.  `make tests` is really intended for development use.  If you have a symptom where mbpfan does not work under normal use please open a new issue.
