### ISSUE TITLE
fix/improvement suggestion (fan's speed adjustment fault)

### ISSUE THREAD

**Issue by Markospoko** [linux-on-mac/mbpfan#203]
There was an attempt to dubiously explain the issue here: [https://github.com/linux-on-mac/mbpfan/issues/170#issue-391942696](url) and here: [https://github.com/linux-on-mac/mbpfan/issues/170#issuecomment-461840333](url), this gives a better clue about it.

_**what isn't good:**_ if I put 40 as low_temp and it's 60C when Mbpfan starts, it won't function correctly, fan speed can be stuck, I know it's said to put 55- something but a properly written fan control program shouldn't work like that

_**correct operation:**_ taking min_fan_speed and max_fan_speed into account, fan's speed should be adjusted according to the temperature, f.e. if you have 60C and 40C is set as low_temp, it should start changing fan's speed smoothly to reach the correct speed for 60C taking actively into account that if temperature drops say to 55C while changing, it should calculate speed accordingly so new target speed is for 55C, not 60C.

**Comment by hyperair** [comment]
Here's the comment from the source code with better descriptions on what the temperature thresholds mean: https://github.com/linux-on-mac/mbpfan/blob/52d897374d25fc7fc1d34425b93958aa583a0c64/src/mbpfan.c#L57-L59

Perhaps we need to update `mbpfan.conf` comments to match that.

**Comment by Markospoko** [comment]
The rest of suggestion also.

**Comment by gaul** [comment]
Could someone send a pull request to improve these descriptions?

**Comment by Markospoko** [comment]
It would be good if there was pull for "correct operation:" part as well.

**Comment by hyperair** [comment]
> correct operation: taking min_fan_speed and max_fan_speed into account, fan's speed should be adjusted according to the temperature, f.e. if you have 60C and 40C is set as low_temp, it should start changing fan's speed smoothly to reach the correct speed for 60C taking actively into account that if temperature drops say to 55C while changing, it should calculate speed accordingly so new target speed is for 55C, not 60C.

I suspect that what's considered "correct operation" is slightly contentious. From what I can tell, the author had a specific idea of what "correct operation" means when this algorithm was designed, and it sounds like you have a different idea of what "correct operation" entails, whereas I think a PID algorithm works better for controlling my fans speed to try to match my fan speeds to the wattage of heat generation happening within my machine: https://github.com/hyperair/mbpfan/tree/pid-algo

**Comment by Markospoko** [comment]
Yes but I think it was about making it better, f.e. if you designed a toy car that could go straight, turn a bit left and right I could say that it could turn more left and right, go slightly faster but it wouldn't have to be different car, say Ferrari, as it used to be but modded, it wasn't technical description, only casual clues. However, did you write that yours is an upped one, different operation? I would be fine to try it if you linked that version?
