### ISSUE TITLE
Enhancement Request: Fan Speeds based on different temperature sensors

### ISSUE THREAD

**Issue by bplein** [linux-on-mac/mbpfan#207]
Correct me if I am wrong, but I believe that a single temperature is used to adjust all fan speeds. 

On multi-fan systems like the older "classic" Mac Pros (cMP), it would be ideal of the CPU temps drove EXHAUST, INTAKE, BOOSTA (and BOOSTB on dual socket), while other sensors drove PS speed and PCI speed. 

I don't think there's a single generic approach to this, which is the complicating factor here. 

I have a MP4,1 (firmware flashed to 5,1) and can provide sensor names etc. 

Thoughts?

**Comment by gaul** [comment]
@bplein You are correct and mbpfan should include this functionality.  Unfortunately I don't have a desktop Mac so I cannot experiment with this myself.  We would gladly accept pull requests to do so, however, and the code is straightforward so you may be able to add this yourself.

@atishma Any chance you could look into this?

**Comment by bplein** [comment]
I appreciate the response. 

I'm not a C coder, but am willing to help test. 

In any event, I ran some tests by manually setting the PCI fan faster, and it didn't appreciably reduce the PCI Ambient sensor temperature. 

I have a unique problem in that I have Fusion-io cards which can run hot, but don't increase the PCIe Ambient sensor fast enough anyhow. I think what I need to do is have my own script that will pull their temps (via a program I can run periodically) and increase PCI fans if a temperature emergency exists. 

Luckily at least in static testing, I can override mbpfan for the PCI fan and it "sticks". I assume that if mbpfan started reacting to elevated temps, it would reset the fan speed as well. Anyhow, I don't believe my problem will be solved by basing the PCI fans on the Te1P sensor.

**Comment by startergo** [comment]
> @bplein You are correct and mbpfan should include this functionality. Unfortunately I don't have a desktop Mac so I cannot experiment with this myself. We would gladly accept pull requests to do so, however, and the code is straightforward so you may be able to add this yourself.
> 
> @atishma Any chance you could look into this?

So these are the MFC settings. How can they be translated to mbpfan settings?:

```

Macs Fan Control 1.5.6 [Qt 5.13.2]
MacPro5,1
CPU: Intel(R) Xeon(R) CPU X5690 @ 3.47GHz [6 cores]
GPU: Radeon RX 480, Radeon RX 480
macOS 10.15.4

Fans:
PCI-min{800}curr{800}max{4500}mode{0}
PS-min{600}curr{848}max{2800}mode{2,Tp1C,31,41}
EXHAUST-min{600}curr{600}max{2800}mode{0}
INTAKE-min{600}curr{1768}max{2800}mode{2,TN0D,53,63}
BOOSTA-min{800}curr{3259}max{5200}mode{2,TN0D,53,63}
BOOSTB-min{800}curr{1112}max{5200}mode{0}


TempSensors:
TA0P (Ambient) - 30.3125, 30.3125
TCAC (CPU A core from PCECI) - 40.0625, 59.9375
TCAD (CPU A Diode) - 41, 41
TCAG () - 80, 80
TCAH (CPU A HeatSink) - 38.125, 38.125
TCAS () - 38.125, 38.125
TCBC (CPU B core from PCECI) - 29.5, 70.5
TCBD (CPU B Diode) - 34.125, 34.125
TCBG () - 80, 80
TCBH (CPU B HeatSink) - 30.75, 30.75
TCBS () - 30.75, 30.75
TH1F () - 31.1484, 31.1484
TH1P (Drive Bay 0) - 31.25, 31.25
TH1V () - 34.2188, 34.2188
TH2F () - 32.5156, 32.5156
TH2P (Drive Bay 1) - 32.625, 32.625
TH2V () - 31.6016, 31.6016
TH3F () - 33.1211, 33.1211
TH3P (Drive Bay 2) - 33.25, 33.25
TH3V () - 33.8281, 33.8281
TH4F () - 31.5898, 31.5898
TH4P (Drive Bay 3) - 31.625, 31.625
TH4V () - 34, 34
THPS () - 34.2188, 34.2188
THTG () - 58, 58
TM1P (DIMM Proximity 1) - 35.25, 35.25
TM2P (DIMM Proximity 2) - 36, 36
TM3P (DIMM Proximity 3) - 37.375, 37.375
TM4P (DIMM Proximity 4) - 37, 37
TM5P (DIMM Proximity 5) - 37.625, 37.625
TM6P (DIMM Proximity 6) - 39.75, 39.75
TM7P (DIMM Proximity 7) - 36.875, 36.875
TM8P (DIMM Proximity 8) - 28.75, 28.75
TMA1 () - 39, 39
TMA2 () - 41.5, 41.5
TMA3 () - 41.75, 41.75
TMA4 () - 41.5, 41.5
TMB1 () - 32.25, 32.25
TMB2 () - 33, 33
TMB3 () - 32.5, 32.5
TMB4 () - 32, 32
TMHS () - 41.75, 41.75
TMLS () - 32, 32
TMPS () - 41.75, 41.75
TMPV () - 38.9688, 38.9688
TMTG () - 75, 75
TN0D (Northbridge Diode) - 58.875, 58.875
TN0H (Northbridge Heatsink) - 46.75, 46.75
TNTG () - 65, 65
Te1F () - 128, 128
Te1P (PCIE Ambient) - 33.125, 33.125
Te1S () - 128, 128
Te2F () - 129, 129
Te2S () - 129, 129
Te3F () - 129, 129
Te3S () - 129, 129
Te4F () - 129, 129
Te4S () - 129, 129
Te5F () - 129, 129
Te5S () - 129, 129
TeGG () - 85, 85
TeGP () - 0, 0
TeRG () - 60, 60
TeRP () - 0, 0
Tp0C (PSMI Supply AC/DC Supply 1) - 37.2031, 37.2031
Tp1C (PSMI Supply AC/DC Supply 2) - 34.3594, 34.3594
TpPS () - 37.2031, 37.2031
TpTG () - 90, 90


Disk drives:
Samsung SSD 970 PRO 512GB - 42
OWC Aura P12 480GB - 41
OWC Aura P12 480GB - 41
OWC Aura P12 480GB - 41
OWC Aura P12 480GB - 41
Samsung SSD 840 Series - 37
OWC Mercury Electra 6G SSD - 36
WDC WD50EZRX-00MVLB1 - 32
WDC WD2500AAJS-75M0A0 - 34
ADATA SU800 - 38
WDC WD1001FALS-403AA0 - 35

```
