### ISSUE TITLE
mbpfan spams systemlogs

### ISSUE THREAD

**Issue by ssbarnea** [linux-on-mac/mbpfan#208]
Apparently my journald is full of logs from mpbfan service and I see no documented option for silencing these messages.
```
Dec 04 21:56:36 smini mbpfan[501]: Sleeping for 7 seconds
Dec 04 21:56:36 smini mbpfan[501]: Old Temp 73: New Temp: 73, Fan Speed: 3350
Dec 04 21:56:36 smini mbpfan[501]: Sleeping for 7 seconds
Dec 04 21:56:36 smini mbpfan[501]: Old Temp 73: New Temp: 73, Fan Speed: 3350
Dec 04 21:56:36 smini mbpfan[501]: Sleeping for 7 seconds
Dec 04 21:56:36 smini mbpfan[501]: Old Temp 73: New Temp: 73, Fan Speed: 3350
```

Is there a way to make mbpfan less spamming? ... other than removing the service ;)

**Comment by gaul** [comment]
@ssbarnea Could you remove `-v` from your command line?

**Comment by gaul** [comment]
Please reopen if the suggested workaround does not suffice.
