### ISSUE TITLE
MacBook 2018+, T2 Support

### ISSUE THREAD

**Issue by kokowang** [linux-on-mac/mbpfan#210]
Apple has moved smc functionality into the T2 chip. Attempting to load **applesmc** results in `Module 'applesmc' is built in`. Thus it is not listed in lsmod and also is not detected by mbpfan.

Macbook Pro 2019 (15,1) | Arch | Linux 5.4.10

**Comment by gaul** [comment]
@kokowang did you get mbpfan working or did you need some workaround?

**Comment by kokowang** [comment]
@gaul I was not able to get mbpfan to work. Issue closed since establishing communication with the T2 seems to be outside the scope of this project.
I'm looking into possible workarounds; been able to read sensors from applesmc but am still unable to change fan speeds.

**Comment by gaul** [comment]
Could you include the logs from `mbpfan -v -f`?  I would like to make sure the error messages are at least clear.
