### ISSUE TITLE
Update program version to 2.2.1

### ISSUE THREAD

**Issue by pacoon** [linux-on-mac/mbpfan#213]
Hello,

currently release 2.2.1 shows "mbpfan 2.2.0 starting up" at startup.

This patch fixes the version.

https://github.com/pacoon/mbpfan/commit/d9030c9879876c0ac71c69892751595d19c2f65d

**Comment by pacoon** [comment]
From d9f84938b8c0eec749deb722a595a9d84bdb45f8 Mon Sep 17 00:00:00 2001
From: Rene Saavedra <pacoon@protonmail.com>
Date: Sat, 21 Mar 2020 14:48:31 -0600
Subject: [PATCH] Update program version to 2.2.1.

---
 src/main.c | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/src/main.c b/src/main.c
index 2b797c9..12df9ce 100644
--- a/src/main.c
+++ b/src/main.c
@@ -1,6 +1,7 @@
 /**
  *  Copyright (C) (2012-present) Daniel Graziotin <daniel@ineed.coffee>
  *  Modifications (2017-present) by Robert Musial <rmusial@fastmail.com>
+ *  Modifications (2020-present) by Rene Saavedra <pacoon@protonmail.com>
  *
  *  This program is free software: you can redistribute it and/or modify
  *  it under the terms of the GNU General Public License as published by
@@ -37,7 +38,7 @@ int daemonize = 1;
 int verbose = 0;
 
 const char *PROGRAM_NAME = "mbpfan";
-const char *PROGRAM_VERSION = "2.2.0";
+const char *PROGRAM_VERSION = "2.2.1";
 const char *PROGRAM_PID = "/var/run/mbpfan.pid";
 
 const char *CORETEMP_PATH = "/sys/devices/platform/coretemp.0";
-- 
2.21.0

**Comment by gaul** [comment]
We can't change the existing release but I'll leave this open to remind me to change the version for the next release.
