### ISSUE TITLE
Failing due to temp sensor paths being moved under applesmc Linux 5.6

### ISSUE THREAD

**Issue by paulyc** [linux-on-mac/mbpfan#214]
On my MBP10,2 running Linux 5.6 rc7,  all the temp sensors are showing up in one big list of tempX_input tempX_label under /sys/devices/platform/applesmc.768 where X is in the range [1,29]. Unsure whether it's this particular model , something I did to my kernel configs, or, /sys interface changed again somewhere between Linux 3.4 and 5.6 or when exactly they changed (most likely imo since it changed once before after all), but it should be a pretty simple fix... for my machine.

The harder part needing some work will be detecting which of the possibly three (!) /sys interfaces your machine has and using the right one in a maintainable way. (Maybe, the ancient pre-3.4 stuff can be "deprecated" read, deleted in the next minor revision staying true to the Apple ethos ;-) but I won't make that call before submitting a PR as I'm not the maintainer for now anyway ;-)

So I can certainly fix mine;  reworking all of the detection code might be a bigger project but figured I'd just leave this note here for anyone else who likes living dangerously on the bleeding edge of github.com/torvalds/linux, and future generations who get it stock

**Comment by gaul** [comment]
I upgraded my MacBook Air 6,2 to Fedora 32 beta with kernel 5.6.0-0.rc7 and cannot reproduce your symptoms.  Can you provide more context on your issue, including the output of `mbpfan -f -v`?

**Comment by paulyc** [comment]
Ah, actually does seem to have been a kernel config issue. When I built applesmc and coretemp into the kernel rather than as modules everything showed up in the expected place in coretemp. I think the module was being loaded in the wrong order, like before applesmc maybe, but it also didn't have any  dependencies on other modules so... Kernel build system bug? Kernel build system user error? 😂 Doesn't seem like that should be possible without at least getting a warning if not an error during the build so I'll go file it under torvalds/linux 😉
