### ISSUE TITLE
Error: max_fan_speed value is not 6200

### ISSUE THREAD

**Issue by Frankjaro** [linux-on-mac/mbpfan#215]
I tried to install it on my iMac mid 2011 (Manjaro XFCE OS) and I get the error "Error: max_fan_speed value is not 6200" . Other users are reporting this issue. Any way to fix it as many ppls are using iMacs with Arch distributions? Thanks for your wonderful work!!!

**Comment by gaul** [comment]
Do you see this error when running the tests?  If so you can safely ignore this.  The test needs to be adapted for non-MacBooks.

**Comment by Frankjaro** [comment]
hello and thanks for reaching back. I never did the test. I get the error at the end of the installation.  Have a look at the screenshot. I never run the test...
![Istantanea_2020-04-30_10-14-02](https://user-images.githubusercontent.com/64580312/80688665-7474e200-8acc-11ea-9c8d-3e0054ba2137.png)

**Comment by Frankjaro** [comment]
running ps aux | grep mbpfan

Returns with: frances+   87732  0.0  0.0   6308  2304 pts/0    S+   11:35   0:00 grep --colour=auto mbpfan

I still dont know if it is running or not...

**Comment by gaul** [comment]
Possibly an issue with the Arch/Manjaro packaging.  Maybe easier to just fix the test.  Can you run:

```
cat /sys/devices/platform/applesmc.768/fan*max
```

I don't have an iMac so I need some help to fix it.

**Comment by Frankjaro** [comment]
Hey! Thanks for your help. Here is the result:

[username@username-imac121 ~]$ cat /sys/devices/platform/applesmc.768/fan*max
4350
6300
2600

**Comment by gaul** [comment]
Please run `mbpfan -t` with the latest master.  However, this appears to be an Arch package issue so I will need to create another release.

**Comment by Frankjaro** [comment]
Please bear me...I am a total noob...I guess when you say "Latest master" you mean the latest release (2.2.1.r2.gbc71232), right?

if so, here is the result:

sudo mbpfan -t

Starting the tests..
It is normal for them to take a bit to finish.
Error: max_fan_speed value is not 6200 
Tests run: 5

Thanks again for your patience

**Comment by gaul** [comment]
You would need to check out the latest source code and build it which may be educational.  But this does not change your Arch package since they will need to repackage this source code.

**Comment by Frankjaro** [comment]
Ok thanks for fixing it! I will try to build it and I will also contact the guy who repckage the build at the Arch page!

**Comment by Frankjaro** [comment]
sorry to bother you again...but I reinstalled the package as you said and now I got this error:

Error: max_fan_speed value is not 2600 

So maybe you just mistyped the value.

Sorry again and thanks

**Comment by Frankjaro** [comment]
my values are:

ODD : 1399 RPM (min = 1400 RPM, max = 4350 RPM)
HDD : 1103 RPM (min = 1100 RPM, max = 6300 RPM)
CPU : 1199 RPM (min = 1200 RPM, max = 2600 RPM)

**Comment by makcuber** [comment]
> You would need to check out the latest source code and build it which may be educational. But this does not change your Arch package since they will need to repackage this source code.

The Arch AUR package is setup as a git package, so when a user pulls the AUR package build files it rebuilds the package from the git source, which means it doesnt need repacking to get updates from the git master branch. Im getting the same error @Frankjaro is reporting in #216 with the max fan speed not 2600 error. I already mentioned my issue in that open ticket, but just wanted to comment here about the way AUR git packages work after seeing the comments on the AUR package page from the package maintainer: https://aur.archlinux.org/packages/mbpfan-git/
