### ISSUE TITLE
Error: max_fan_speed value is not 2600 (old value was 6200)

### ISSUE THREAD

**Issue by Frankjaro** [linux-on-mac/mbpfan#216]
Sorry to bother you again...but I reinstalled the package as you said and now I get this error:

Error: max_fan_speed value is not 2600 

So maybe a value was mistyped?

Sorry again and thanks

My values are:

ODD : 1399 RPM (min = 1400 RPM, max = 4350 RPM)
HDD : 1103 RPM (min = 1100 RPM, max = 6300 RPM)
CPU : 1199 RPM (min = 1200 RPM, max = 2600 RPM)

_Originally posted by @Frankjaro in https://github.com/linux-on-mac/mbpfan/issues/215#issuecomment-621766199_

**Comment by makcuber** [comment]
Having the same issue on a 2012 MBA running Arch. Tried editing the config file located at /etc/mbpfan.conf but it keeps saying it cant find the config file and instead uses the defaults that dont work

**Comment by JanDraak** [comment]
Can confirm having the same issue on 11,1 on fresh arch install when running `sudo mbpfan -t`

**Comment by Frankjaro** [comment]
Yes, the package doesn't work anymore. A few weks ago, I asked the guy who mantains the package to fix the value for iMacs too (as there are  A LOT of iMacs with the same issue. Fans on iMacs don't work...) but he (apparently) mistyped the value (not sure about this...). The max_fan_speed for iMacs is 6300 and as far as I can understand for MBP is 6200. I am a total noob that switched to Manjaro a couple of months ago and I don't have a clue on how to fix it ( I tried to read some documentation on how to fix packages and rebuild them to no avail). A help would be nice. I partially fixed the overheating issue on iMac by using these commands on a bash file (hope it helps):

sudo sh -c  "echo 1600 > /sys/devices/platform/applesmc.768/fan1_min"
sudo sh -c  "echo 2000 > /sys/devices/platform/applesmc.768/fan2_min"
sudo sh -c  "echo 2100 > /sys/devices/platform/applesmc.768/fan3_min"

But it is a pain in the back to type these commands every time I boot Manjaro. Even after resume from suspension I have to type them.  Hope somebody will try to help us. I am willing to learn so even a direction on what to study would be nice. Thanks

**Comment by Frankjaro** [comment]
On my iMac mid 2011 it is working now! It doesnt return with any error any more and I can safely change the values in the mbpfan.conf  safely. 

To whoever did that: GOOD JOB anf thanks!

**Comment by gaul** [comment]
Seems like you found a workaround.
