### ISSUE TITLE
Commit on Apr 30, 2020 breaks compatibility with Macbook Pro 5,5. Previous commit works well.

### ISSUE THREAD

**Issue by elliotwutingfeng** [linux-on-mac/mbpfan#217]
Using a 13 inch Macbook Pro Mid 2009 (5,5) here. The commit 10d6febeb485539ed4be09f584f74f861df10299 causes my setup to throw "Error: max_fan_speed value is not 2600". Fan no longer spins up when temperature is high. I resolved it by checking out commit bc71232af281e73f9c47d1b45fcb6ae284daf480 and recompiling.

Edit: I was wrong earlier about the "Error: max_fan_speed value is not 2600" issue. It turns out that in both revisions, 'sudo mpbfan -t' only passes all tests if it is run from the mbpfan folder. Is this intended behavior?

**Comment by sancarr** [comment]
Hello @elliotwutingfeng 
Would you be able to share with me the process of how you installed the earlier version from the commit? I am new to Linunx/Manjaro so I am having trouble understanding what to do.

Thank you,

**Comment by gaul** [comment]
@elliotwutingfeng how does this break your setup?  This is a test-only configuration that should not be run by most users.

**Comment by elliotwutingfeng** [comment]
I did a HTML5 stress test comparison (https://www.antutu.com/html5/) between revisions bc71232 and 10d6feb and monitored the fan speed RPM using 'watch sensors'. In 10d6feb, the RPM remained at ~3100 consistently while in bc71232, the speeds gradually increased from ~2000 RPM to ~4300 RPM before going back down.

I was wrong earlier about the "Error: max_fan_speed value is not 2600" issue. It turns out that in both revisions, 'sudo mpbfan -t' only passes all tests if it is run from the mbpfan folder. Is this intended behavior?

Otherwise, you will get "Error: max_fan_speed value is not 6200" for bc71232, and "Error: max_fan_speed value is not 2600" for 10d6feb respectively.
