### ISSUE TITLE
<stdlib.h> not found compiling with $make

### ISSUE THREAD

**Issue by amruizva** [linux-on-mac/mbpfan#225]
System:
Operating System: Linux Mint 20
Kernel: Linux 5.4.0-26-generic

Fatal error compiling with make:

Output:

Compiling src/settings...
cc -c  -g  -Wall -Wextra -Wno-unused-function -std=c99 -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=500 src/settings.c -osrc/settings.o
In file included from src/settings.c:37:
src/settings.h:34:10: fatal error: stdlib.h: No such file or directory
   34 | #include <stdlib.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:33: src/settings.o] Error 1

**Comment by gaul** [comment]
C89 includes stdlib.h which has been part of the standard for over 30 years.  Perhaps something is wrong with your environment?

**Comment by gaul** [comment]
Please reopen if symtoms persist.
