### ISSUE TITLE
Error: max_fan_speed value is not 6200

### ISSUE THREAD

**Issue by sebadamus** [linux-on-mac/mbpfan#226]
Hi, I came to try mbpfan on my MBP 8.2 on Linux Mint Cinnamon 20 (I came from macfanctld, this one seems to consume about 2% cpu... so giving it a try to mbpfan)

When I run mbpfan -t it gives this error:
Error: max_fan_speed value is not 6200
Dont know if it is just ok and dont have to worry.

coretemp and applesmc are detected, hope this is ok
voidnull0@mint-mpb:~$ lsmod | grep -e applesmc -e coretemp
applesmc               20480  0
input_polldev          20480  1 applesmc
coretemp               20480  0

**Comment by ysguy** [comment]
Same issue on a 2011 iMac 27.

**Comment by ysguy** [comment]
Try this as a maybe on a fix: echo "1" /sys/devices/platform/applesmc.768/fan1_manual
Seems to have shut up my dmesg output and fans seem to still cycle properly.

**Comment by JoanGitHubUser** [comment]
Same here on a MBP 10,1 15" Retina from 2012. I have edited /etc/mbpfan.conf manually, but dos not cause any effect. After the echo, do we need to reboot or is plug&play ?

**Comment by gaul** [comment]
Don't worry about it.  These tests were not designed with a wide range of Apple hardware and spuriously fail on models which don't have the same fan speed limits.  The next version will remove this flag.
