### ISSUE TITLE
Debian and/or Ubuntu package

### ISSUE THREAD

**Issue by gaul** [linux-on-mac/mbpfan#230]
It would be great if someone could contribute a PPA or main repository package for Debian and/or Ubuntu

**Comment by satmandu** [comment]
Is this resolved by debian packaging this here: https://salsa.debian.org/debian/mbpfan
Also here: https://packages.debian.org/source/sid/mbpfan

**Comment by gaul** [comment]
Thanks for noticing this!  But I think I filed an invalid issue since the README already recommends this:

https://github.com/linux-on-mac/mbpfan#debian
