### ISSUE TITLE
Feauture Request: Intelligent cooling mode(s)

### ISSUE THREAD

**Issue by arch-user-france1** [linux-on-mac/mbpfan#240]
I would like an intelligent cooling mode like apple already has

If the CPU temperate is 80 degrees, nothing happens but if it is like 90 for 1 minute then the fans begin spinning a lot faster
I like this feauture but I just hate that it's so long to trigger. 

Maybe if you're bored you might want to do a customizable intelligent cooling mode?

**Comment by gaul** [comment]
I think mbpfan already works this way?  You can use `mbpfan -f -v` to see what it is doing and configure the behavior via the config file.

**Comment by arch-user-france1** [comment]
I'm not sure but what I know is that apple systems don't overheat usually, or only a little bit.
The problem is apple's cooling system, how it works, itself!

I'm not using mbpfan anymore.. So I will close that.
