### ISSUE TITLE
Release version 2.3.0

### ISSUE THREAD

**Issue by gaul** [linux-on-mac/mbpfan#247]
There are few new commits https://github.com/linux-on-mac/mbpfan/compare/v2.2.1...master but this removes the misleading tests from the main binary in 52d897374d25fc7fc1d34425b93958aa583a0c64.  Need to bump the version number and review any outstanding PRs.

**Comment by LyesSaadi** [comment]
Hey :wave: ! Could you tag & release?

**Comment by gaul** [comment]
Done: https://github.com/linux-on-mac/mbpfan/releases/tag/v2.3.0

**Comment by LyesSaadi** [comment]
Thank you!
