### ISSUE TITLE
How can I add a new repository to linux-on-mac ?

### ISSUE THREAD

**Issue by flagsoft** [linux-on-mac/mbpfan#267]
How can I add a new repository to linux-on-mac (group? or what is it) ?

**Comment by gaul** [comment]
What repository would you like to make?  The only live one here is mbpfan.  I forked the others as pointers to the parent repos.

**Comment by flagsoft** [comment]
Can you add this one: https://github.com/flagsoft/How-to-make-Linux-audio-sound-working-on-Mac-Hardware

**Comment by gaul** [comment]
Done.
